# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "geerlingguy/ubuntu2004"
  config.vm.provider :virtualbox do |vb|

    # Customize the VM
    vb.name = "ubuntu-vm"
    vb.check_guest_additions = false
    vb.cpus = 1
    vb.memory = 1024

  config.vm.provision "shell", inline: <<-SHELL
    # Put your script here
    sudo apt-get update && sudo apt-get install htop neofetch -y
  SHELL
  end
end